version: '3.8'
services:
#  mysql:
#    image: mysql:8.0
#    restart: always
#    ports:
#      - "3306:3306"
#    environment:
#      MYSQL_DATABASE: teamguu
#      MYSQL_USER: teamguu
#      MYSQL_PASSWORD: 1234
#      MYSQL_ROOT_PASSWORD: 1234

  redis:
    image: redis
    ports:
      - "6379:6379"

  app:
    build: .
    restart: always
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://teamguu-database.c7vs4xjkmcxm.ap-northeast-2.rds.amazonaws.com:3306/teamguu-database
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: teamguu!
    depends_on:
#      - mysql
      - redis
